spring.application.name=screensound
spring.datasource.url=jdbc:mysql://localhost:3306/screensound?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password=${DB_PASSWORD}

